import { randomUUID } from 'node:crypto';
import { afterAll, beforeAll, expect, it } from 'vitest';
import { eq } from 'drizzle-orm';
import { createDb, companies, companyMemberships, agents, issues, heartbeatRuns, issueThreadInteractions } from '@paperclipai/db';
import { getAppStoreDefinition, getAvailableConnectionMethod, connectionMethodSupportsAutomaticOAuth, connectionMethodRequiresConfiguration, appDefinitionSchema } from '@paperclipai/shared';
import { connectionIntentService } from '../services/connection-intents.js';
import { startEmbeddedPostgresTestDatabase } from './helpers/embedded-postgres.js';
let database: Awaited<ReturnType<typeof startEmbeddedPostgresTestDatabase>>;
let db: ReturnType<typeof createDb>;
beforeAll(async () => { database = await startEmbeddedPostgresTestDatabase('figma-setup-'); db = createDb(database.connectionString); });
afterAll(async () => { await database?.cleanup(); });
it('offers native automatic OAuth setup without customer secrets or implicit inspection grants', async () => {
  const app = getAppStoreDefinition('figma')!;
  expect(appDefinitionSchema.safeParse(app).success).toBe(true);
  const method = getAvailableConnectionMethod(app)!;
  expect(connectionMethodSupportsAutomaticOAuth(method)).toBe(true);
  expect(connectionMethodRequiresConfiguration(method)).toBe(false);
  expect(method.defaults?.serverUrl).toBe('https://mcp.figma.com/mcp');
  expect(method.ownershipModes).toEqual(['dcr']);
  const companyId = randomUUID(), agentId = randomUUID(), issueId = randomUUID(), runId = randomUUID();
  await db.insert(companies).values({ id: companyId, name: 'Isolated Figma setup', issuePrefix: 'FST' });
  await db.insert(companyMemberships).values({ companyId, principalType: 'user', principalId: 'fixture-board', status: 'active', membershipRole: 'member' });
  await db.insert(agents).values({ id: agentId, companyId, name: 'Fixture employee', role: 'engineer', status: 'active', adapterType: 'process' });
  await db.insert(issues).values({ id: issueId, companyId, title: 'Synthetic Figma setup', status: 'in_progress', assigneeAgentId: agentId });
  await db.insert(heartbeatRuns).values({ id: runId, companyId, agentId, status: 'running', responsibleUserId: 'fixture-board', contextSnapshot: { issueId } });
  const claims = { sub: agentId, company_id: companyId, run_id: runId, responsible_user_id: 'fixture-board' };
  const service = connectionIntentService(db);
  expect((await service.search(claims, 'Figma')).results).toEqual([expect.objectContaining({ service: 'figma', state: 'available', connectionId: null })]);
  const first = await service.request(claims, 'figma');
  expect(first.state).toBe('needs_user_action');
  expect((await service.request(claims, 'figma')).interactionId).toBe(first.interactionId);
  const [saved] = await db.select().from(issueThreadInteractions).where(eq(issueThreadInteractions.id, first.interactionId!));
  expect(saved.kind).toBe('connection_intent');
  expect(saved.addresseeUserId).toBe('fixture-board');
  expect(saved.companyId).toBe(companyId);
  expect(saved.status).toBe('pending');
  const setup = await service.setupOptions(first.interactionId!);
  expect(setup.service.methods).toEqual([{ key: 'mcp-oauth', label: 'mcp-oauth', auth: 'oauth' }]);
  expect(setup.existingConnections).toEqual([]);
  // A setup card never implies a usable connection, grants, or a live login.
  expect((await service.search(claims, 'Figma')).results[0].state).toBe('available');
  await expect(service.search({ ...claims, company_id: randomUUID() }, 'Figma')).rejects.toThrow();
});
